# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app
# Install all dependencies including dev for tsx and types
COPY package*.json tsconfig.json .
RUN npm install
# Copy source
COPY src ./src
# CMD: run server via tsx
ENTRYPOINT ["npx", "tsx", "src/server.ts"]
